server:
  port: 8080

spring:
  task: # Asynchronous task configuration
    execution:
      pool:
        core-size: 1
        max-size: 2
        queue-capacity: 2
      thread-name-prefix: async-thread-
    scheduling: # Scheduling task configuration
      pool:
        size: 2
      thread-name-prefix: scheduled-thread-

logging:
  level:
    com:
#      vedha: debug

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    env:
      enabled: true
    configprops:
      show-values: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true